export const FindARideHeaderTitle = "Find a Ride"
export const MyListingsHeaderTitle = "My Listings"
export const PostARideHeaderTitle = "Post a Ride"
export const LoginHeaderTitle = "Login"
export const SignupHeaderTitle = "Signup"
export const AddACarHeaderTitle = "Add a car"
